### ISSUE TITLE
List of morses 

### ISSUE THREAD

**Issue by kmaslowiec** [kmaslowiec/mors_app#6]
- [ ] create fragement and view model
- [ ] add it to koin
- [ ] add Recycle View wit 'diff' 
- [ ] link it with boom app icon

**Comment by kmaslowiec** [comment]
The item displays date and time of morsing in descending order.
